[build-system]
requires      = ["setuptools>=64", "setuptools_scm>=8", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "todo_package_name"
requires-python = ">=3.9"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-mock"
]

[tool.setuptools_scm]
root = "../.."
